# Generated by Django 5.0.3 on 2024-03-20 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fxd', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
