# Generated by Django 5.0.3 on 2024-03-27 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fxd', '0006_rename_calories_calorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calorie',
            old_name='query',
            new_name='foods',
        ),
    ]
