# Generated by Django 5.0.3 on 2024-04-08 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fxd', '0011_conta_delete_cont'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='gender',
        ),
    ]
