# Generated by Django 5.0.3 on 2024-04-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxd', '0012_remove_conta_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='city',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='country',
        ),
        migrations.AlterField(
            model_name='conta',
            name='contactno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='conta',
            name='postalcode',
            field=models.CharField(max_length=20),
        ),
    ]
