# Generated by Django 5.0.3 on 2024-03-26 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fxd', '0004_rename_login_main'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='main',
            new_name='calories',
        ),
        migrations.RenameField(
            model_name='calories',
            old_name='confirmpassword',
            new_name='batchno',
        ),
        migrations.RenameField(
            model_name='calories',
            old_name='password',
            new_name='query',
        ),
    ]
