# Generated by Django 5.0.3 on 2024-03-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxd', '0008_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
